[package]
name = "cvm-indexer"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[lib]
name = "market_indexer"
path = "src/lib.rs"

[dependencies]
alloy = { version = "1.7.3", features = ["full"] }
anyhow = "1.0.102"
bigdecimal = "0.4.10"
clap = { version = "4.6.0", features = ["derive"] }
diesel = { version = "2.3.7", features = ["numeric", "postgres"] }
diesel_migrations = { version = "2.3.1", features = ["postgres"] }
dotenvy = "0.15.7"
ethp = "0.1.0"
openssl = { version = "0.10", features = ["vendored"] }
pq-sys = { version = "0.7", features = ["bundled"] }
tokio = { version = "1.50.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
