[package]
name = "market-indexer-evm"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[dependencies]
alloy = { version = "1.8.3", features = ["full"] }
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
diesel = { version = "2.3.7", features = ["postgres"] }
dotenvy = "0.15.7"
indexer-framework = { version = "0.1.0", path = "../framework" }
tokio = { version = "1.50.0", features = ["full"] }
tokio-retry = "0.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[profile.dev]
panic = "abort"
